version: '3.8'
services:
  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: nyc_taxi_data
    ports:
      - "5432:5432"

  loader:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      PGPASSWORD: mypass
    links:
      - db
