version: '3.8'
services:
  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: nyc_taxi_data
    ports:
      - "5432:5432"

  loader:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      PGPASSWORD: mypass
    links:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
